version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
      - 80:80

  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd

volumes:
  db-data:
